algoritmo "reaisDolar"
// Função : algoritmo que converte o valor digitado em dolar , um dolar igual 3,45
// Autor :  tiago raug
// Data : 25/10/2022
// Seção de Declarações 
var
   valorreais,valordolar:real
inicio
// Seção de Comandos
   escreval("digite valor em reais que possui na carteira ")
   leia(valorreais)
   valordolar:= valorreais*3.45
   escreval("voce tem em dolar",valordolar:5:2)
   escreval("  FIM DO PROGRAMA   ")
fimalgoritmo
